[package]
name = "cratefind"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
dirs = "6"
fastembed = "5.8.0"
octonion = "0.1.1"
rusqlite = { version = "0.35", features = ["bundled"] }
syn = { version = "2", features = ["full", "parsing", "visit"] }
